name: graduation_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  booking_calendar: ^1.1.10
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  geolocator: ^14.0.0
  get: ^4.6.6
  google_maps_flutter: ^2.10.0
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.18.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/tipsAndTricksPhotos/
    - assets/lang/en.json
    - assets/lang/ar.json
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
    - family: RacingSansOne
      fonts:
        - asset: assets/fonts/RacingSansOne-Regular.ttf

flutter_assets:
  assets_path: assets/images
  output_path: lib/utils
  filename: appImages.dart
  field_prefix:
